[package]
name = "lantern-core"
version.workspace = true
edition.workspace = true

[dependencies]
lantern-proto.workspace = true
lantern-crypto.workspace = true
lantern-discovery.workspace = true
lantern-transport.workspace = true
lantern-store.workspace = true
tokio.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
uuid.workspace = true
quinn.workspace = true
hex.workspace = true
rand.workspace = true
blake3 = { workspace = true, features = ["mmap", "rayon"] }
